CUDA_VISIBLE_DEVICES=5,6,7 python -m torch.distributed.launch \
        --nproc_per_node=3 \
        --master_port=32002 \
        --use_env \
        main.py \
        --pretrained params/detr-r100-pre-vcoco.pth \
        --output_dir logs/detr-r100-cpc-mca-vcoco-115-bs4 \
        --hoi \
        --epochs 90 \
        --batch_size 4 \
        --dataset_file vcoco \
        --hoi_path data/v-coco \
        --num_obj_classes 81 \
        --num_verb_classes 29 \
        --backbone resnet101 \
        --set_cost_bbox 2.5 \
        --set_cost_giou 1 \
        --bbox_loss_coef 2.5 \
        --giou_loss_coef 1 \
        --sub_loss_aug_coef 1 \
        --obj_loss_aug_coef 1 \
        --verb_loss_aug_coef 0.5